version: '2'

services:

  elasticsearch:
    build:
      context: elasticsearch/
    volumes:
      - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
        #    ports:
        #      - "9200:9200"
    networks:
      - honeypot
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"

  logstash:
    build:
      context: logstash/
    volumes:
      - ./logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml:ro
      - ./logstash/pipeline:/usr/share/logstash/pipeline:ro
    ports:
      - "5045:5045"
    networks:
      - honeypot
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
    depends_on:
      - elasticsearch

  kibana:
    build:
      context: kibana/
    volumes:
      - ./kibana/config/:/usr/share/kibana/config:ro
    networks:
      - honeypot
    depends_on:
      - elasticsearch

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/config:/etc/nginx/conf.d:ro,Z
      - ./nginx/htpasswd.users:/etc/nginx/htpasswd.users:ro,Z
    ports:
      - "5601:5601"
    networks:
      - honeypot
    depends_on:
      - kibana

  kippo:
    build:
      context: kippo/
    ports:
      - "2222:2222"
    networks:
      - honeypot
    depends_on:
      - elasticsearch

networks:
  honeypot:
    driver: bridge
