# https://github.com/elastic/kibana-docker
#FROM docker.elastic.co/kibana/kibana-oss:6.1.0
FROM docker.elastic.co/kibana/kibana:5.5.3

# Add your kibana plugins setup here
# Example: RUN kibana-plugin install <name|url>
